#
# Example MySQL v8 Stack
#
# Updated 20190908.1

version: "3.5"

services:
      
  db:
    image: mysql:8
    restart: always
    environment:
        MYSQL_DATABASE: demo_db
        MYSQL_ROOT_PASSWORD: example
        MYSQL_USER: demouser
        MYSQL_PASSWORD: example
    networks:
      - admin_webnet

  tool_phpmyadmin: 
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
        PMA_HOST: db
    ports:
      - "$PHPMYADMIN_PORT80:80"
    networks:
      - admin_webnet
      
networks:
  admin_webnet:
    external: true

