#
# Example MySQL5 Stack
#
# Updated 20190908.1

version: "3.5"

services:
      
  db:
    image: postgres:11
    restart: always
    environment:
        MYSQL_DATABASE: demo_db
        MYSQL_ROOT_PASSWORD: example
        MYSQL_USER: demouser
        MYSQL_PASSWORD: example
    networks:
      - admin_webnet

  tool_adminer: 
    image: adminer:4
    restart: always
    environment:
        ADMINER_DEFAULT_SERVER: db
    ports:
      - "$ADMIN_PORT8080:8080"
    networks:
      - admin_webnet
      
networks:
  admin_webnet:
    external: true

