#
# Example MySQL v5 Stack
#
# Updated 20190908.3

version: "3.5"

services:
      
  db:
    image: mysql:5
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
        MYSQL_DATABASE: demo_dbv5
        MYSQL_ROOT_PASSWORD: example
        MYSQL_USER: demouser
        MYSQL_PASSWORD: example
    networks:
      - admin_webnet
    volumes:
      - type: volume
        target: /var/lib/mysql
        source: data_db 

  tool_phpmyadmin: 
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
        PMA_HOST: db
    ports:
      - "$PHPMYADMIN_PORT80:80"
    networks:
      - admin_webnet
      
networks:
  admin_webnet:
    external: true

volumes:
  data_db:
    name: db_mysql5_zcmd_demo  

